name: Eden SCM OSS

on:
  pull_request:
    branches:
      - main

jobs:
  make-oss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run make oss
        working-directory: eden/scm
        run: make oss
