name: Eden SCM OSS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  make-oss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew" >> $GITHUB_ENV
          echo "HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar" >> $GITHUB_ENV
          echo "HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew" >> $GITHUB_ENV

      - name: Install fbthrift (thrift1)
        run: |
          brew install fbthrift

      - name: Run make oss
        working-directory: eden/scm
        run: make oss

      - name: Show Sapling version
        working-directory: eden/scm
        run: ./sl --version
